language: cpp
os:
  - linux
  - osx
dist: trusty
sudo: required

before_install:
  - test $TRAVIS_BRANCH != coverity_scan -o ${TRAVIS_JOB_NUMBER##*.} = 1 || exit 0
  - if [[ $VCMI_PLATFORM == 'linux' ]]; then . .travis.linux; fi
  - if [[ $VCMI_PLATFORM == 'mac' ]]; then . .travis.osx; fi
  - if [[ $VCMI_PLATFORM == 'mxe' ]]; then . .travis.mxe; fi

before_script:
  - mkdir build
  - cd build
  - if [[ $TRAVIS_BRANCH != 'coverity_scan' ]]; then cmake -G "Unix Makefiles" .. $VCMI_CMAKE_FLAGS; fi

script:
  - test $TRAVIS_BRANCH != coverity_scan || exit 0
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then cd ..; xcodebuild -project osx/osx-vcmibuilder/vcmibuilder.xcodeproj/ -configuration Release CONFIGURATION_BUILD_DIR=..; cd build; fi
  - make -j2

env:
  matrix:
    - ignore=this
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "NMg+qtQB4DIZ/KqlDeIn3K7A7Ydksdpnbv6Ha9n4bSSA0AT8wlPwbHXvQmiR8qYs6cnz4fyY6NVcBe7X3bdR8jWyPNAS0l0QByqG12q3dBpEtNNn0X5u/GS3wHse5+ObNAF9a83+xACTQj2UdxqHgJ3LFGzdBpQt3kLsc8NDnn8="

matrix:
  exclude:
    - env: ignore=this
  include:
    - os: linux
      compiler: clang
      env: VCMI_PLATFORM='linux' REAL_CC=clang-3.6 REAL_CXX=clang++-3.6 PACKAGE=clang-3.6 SUPPORT=libstdc++-4.8-dev VCMI_CMAKE_FLAGS='-DENABLE_TEST=0'
    - os: linux
      compiler: clang
      env: VCMI_PLATFORM='linux' REAL_CC=clang-3.5 REAL_CXX=clang++-3.5 PACKAGE=clang-3.5 SUPPORT=libstdc++-4.8-dev VCMI_CMAKE_FLAGS='-DENABLE_TEST=0'
    - os: linux
      compiler: clang
      env: VCMI_PLATFORM='linux' REAL_CC=clang-3.4 REAL_CXX=clang++-3.4 PACKAGE=clang-3.4 SUPPORT=libstdc++-4.8-dev VCMI_CMAKE_FLAGS='-DENABLE_TEST=0'
    - os: linux
      compiler: gcc
      env: VCMI_PLATFORM='linux' REAL_CC=gcc-4.8   REAL_CXX=g++-4.8     PACKAGE=g++-4.8   SUPPORT= VCMI_CMAKE_FLAGS='-DENABLE_TEST=0'
    - os: linux
      env: VCMI_PLATFORM='mxe' MXE_TARGET=i686-w64-mingw32.shared VCMI_CMAKE_FLAGS='-DENABLE_TEST=0'
      sudo: required
    - os: osx
      env: VCMI_PLATFORM='mac'

addons:
  coverity_scan:
    project:
      name: vcmi/vcmi
      description: Build submitted via Travis CI
    notification_email: coverity@arseniyshestakov.com
    build_command_prepend: "cov-configure --compiler clang-3.6 --comptype clangcc && cov-configure --comptype clangcxx --compiler clang++-3.6 && cmake -G Ninja .. -DCMAKE_BUILD_TYPE=DEBUG -DENABLE_LAUNCHER=1 -DENABLE_TEST=0"
    build_command: ninja -j 2
    branch_pattern: coverity_scan

notifications:
  email:
    recipients:
      - vcmi.fail@mixaill.tk
      - saven.ivan@gmail.com
    on_success: change
    on_failure: always
    
after_success:
- wget https://download.vcmi.eu/travis_deploy_rsa.enc
- touch /tmp/travis_deploy_rsa
- chmod 600 /tmp/travis_deploy_rsa
- openssl aes-256-cbc -K $encrypted_1d30f79f8582_key -iv $encrypted_1d30f79f8582_iv -in travis_deploy_rsa.enc -out /tmp/travis_deploy_rsa -d
- eval "$(ssh-agent -s)"
- ssh-add /tmp/travis_deploy_rsa
- sftp -r -P 2222 -o StrictHostKeyChecking=no travis@beholder.vcmi.eu <<< "put -r $TRAVIS_BUILD_DIR /incoming/$TRAVIS_JOB_ID"
